Repository DevOps-Team4-2022/DevOps_Oct2022_Team4_Assignment, pull requests merged in 2023-02, with the labels that each got.

#36 Feature/create companylist and status dropdown
  .idea/DevOps_Oct2022_Team4_Assignment.iml
  .idea/misc.xml
  __pycache__/app.cpython-310.pyc
  __pycache__/app.cpython-39.pyc
  app.py
  excel_files_to_upload/student_data.xlsx
  static/css/main.css
  templates/match_student-DESKTOP-CN7GB4D.html
  templates/match_student.html
  templates/upload_data.html
  tests/__pycache__/test_app_create_data.cpython-39-pytest-7.2.0.pyc
  tests/test_app_create_data.py
Labels: enhancement

#37 Merging feature/create-folder-on-successful-upload to dev
  __pycache__/app.cpython-39.pyc
  app.py
  templates/match_student-DESKTOP-CN7GB4D.html
  tests/__pycache__/test_app_upload_data.cpython-39-pytest-7.2.0.pyc
  tests/dummy_company_data.xlsx
  tests/dummy_student_data.xlsx
  tests/test_app_create_data.py
  tests/test_app_upload_data.py
Labels: enhancement, size_l

#39 Remerge to include new feature from feature/create-folder-on-successful-upload
  app.py
Labels: enhancement, size_s

#40 Update workflow to create database on workflow run for testing purpose
  .github/workflows/CDeliver.yml
  .github/workflows/CDelivery & CDeploy.yml
  .github/workflows/CIntegration-PR.yml
  .github/workflows/CIntegration-Push.yml
  .idea/.gitignore
  .idea/DevOps_Oct2022_Team4_Assignment.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  __pycache__/app.cpython-310.pyc
  __pycache__/app.cpython-39.pyc
  tests/test_app_upload_data.py
Labels: enhancement

#44 Merging unittest/test matchstudent to dev
  .github/workflows/CDelivery & CDeploy.yml
  .github/workflows/CIntegration-PR.yml
  .github/workflows/CIntegration-Push.yml
  .idea/.name
  .idea/DevOps_Oct2022_Team4_Assignment.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  __pycache__/app.cpython-39.pyc
  app.py
  tests/__pycache__/test_app_create_data.cpython-39-pytest-7.2.0.pyc
  tests/__pycache__/test_app_upload_data.cpython-39-pytest-7.2.0.pyc
  tests/dummy_company_data.xlsx
  tests/dummy_student_data.xlsx
  tests/unit-tests/test_app_create_data.py
  tests/unit-tests/test_app_match_student.py
  tests/unit-tests/test_app_upload_data.py
Labels: enhancement, size_m

#45 Merge Dev changes into UAT"
  .github/workflows/CDelivery & CDeploy.yml
  .github/workflows/CIntegration-PR.yml
  .github/workflows/CIntegration-Push.yml
  app.py
  create_db.py
  excel_files_to_upload/company_data.xlsx
  excel_files_to_upload/student_data.xlsx
  static/css/main.css
  templates/base.html
  templates/index.html
  templates/match_student.html
  templates/upload_data.html
  tests/unit-tests/test_app_create_data.py
  tests/unit-tests/test_app_match_student.py
  tests/unit-tests/test_app_upload_data.py
Labels: size_xl

#50 Add xampp-caching, selenium-test-dependencies, monitoring plugins to all CIs
  .github/workflows/CDelivery & CDeploy.yml
  .github/workflows/CIntegration-ON-PR.yml
  .github/workflows/CIntegration-ON-PUSH.yml
  tests/integration-tests/test_upload_data.py
Labels: size_m

#52 Test/test navbar and upload data and match students 1
  tests/integration-tests/0-test_navigationBar.py
  tests/integration-tests/1-test_uploadData.py
  tests/integration-tests/2-test_matchStudent.py
  tests/integration-tests/__pycache__/0-test_navigationBar.cpython-310-pytest-7.1.3.pyc
  tests/integration-tests/__pycache__/1-test_uploadData.cpython-310-pytest-7.1.3.pyc
  tests/integration-tests/__pycache__/2-test_matchStudent.cpython-310-pytest-7.1.3.pyc
  uploaded-data/company_data/2023-02-17_09-49-27_company_data.xlsx
  uploaded-data/student_data/2023-02-17_09-49-18_student_data.xlsx
Labels: size_m

#55 Feature/create emailgeneration and email folder
  app.py
  email/S0194725G_Lau Kai Feng_Resume.msg
  templates/prepare_email.html
  templates/upload_data.html
  tests/integration-tests/2-test_matchStudent.py
  tests/integration-tests/__pycache__/2-test_matchStudent.cpython-311-pytest-7.2.1.pyc
  tests/integration-tests/test_upload_data.py
  tests/unit-tests/test_app_prepare_email.py
Labels: size_m

#57 fix: fix integration test for match student page
  email/S0194725G_Lau Kai Feng_Resume.msg
  tests/integration-tests/2-test_matchStudent.py
  tests/integration-tests/__pycache__/0-test_navigationBar.cpython-310-pytest-7.1.3.pyc
  tests/integration-tests/__pycache__/1-test_uploadData.cpython-310-pytest-7.1.3.pyc
  tests/integration-tests/__pycache__/2-test_matchStudent.cpython-310-pytest-7.1.3.pyc
  tests/integration-tests/__pycache__/2-test_matchStudent.cpython-311-pytest-7.2.1.pyc
  uploaded-data/company_data/2023-02-17_09-49-27_company_data.xlsx
  uploaded-data/student_data/2023-02-17_09-49-18_student_data.xlsx
Labels: size_s

#58 fix: fix integration test for match student page #2
  tests/integration-tests/2-test_matchStudent.py
  tests/integration-tests/__pycache__/2-test_matchStudent.cpython-39-pytest-7.2.0.pyc
Labels: size_s

#59 Merge Dev changes into UAT #2
  .github/workflows/CDelivery & CDeploy.yml
  .github/workflows/CIntegration-ON-PR.yml
  .github/workflows/CIntegration-ON-PUSH.yml
  CHANGELOG.md
  app.py
  package-lock.json
  package.json
  templates/prepare_email.html
  templates/upload_data.html
  tests/integration-tests/0-test_navigationBar.py
  tests/integration-tests/1-test_uploadData.py
  tests/integration-tests/2-test_matchStudent.py
  tests/integration-tests/__pycache__/2-test_matchStudent.cpython-39-pytest-7.2.0.pyc
  tests/unit-tests/test_app_prepare_email.py
Labels: size_m

#60 Deploy to Production
  .github/workflows/CDelivery & CDeploy.yml
  .github/workflows/CIntegration-ON-PR.yml
  .github/workflows/CIntegration-ON-PUSH.yml
  app.py
  templates/prepare_email.html
  templates/upload_data.html
  tests/integration-tests/0-test_navigationBar.py
  tests/integration-tests/1-test_uploadData.py
  tests/integration-tests/2-test_matchStudent.py
  tests/integration-tests/__pycache__/2-test_matchStudent.cpython-39-pytest-7.2.0.pyc
  tests/unit-tests/test_app_prepare_email.py
Labels: size_m
